database:
  name: database_name
  user: !ENV ${DB_USER}
  password: !ENV ${DB_PASS}
  host: !ENV ${DB_HOST}
  port: 5432
ws:
  user: !ENV ${WS_USER}
  password: !ENV ${WS_PASS}
  host: !ENV ‘https://${CURR_ENV}.ws.com.local'
